window.parseLinks = function(container) {
  var parentPath = "";
  if (container.getAttribute("data-currentpath")) {
    parentPath = container.getAttribute("data-currentpath").replace("/", "");
  }
  var links = container.getElementsByTagName("a");
  Array.prototype.forEach.call(
    Array.prototype.filter.call(links, el => {
      var internal = window.RELATIVE.test(el.href);
      console.log('internal', el.href, internal)
      if (!internal) el.classList.add("external");
      el.style.display = "block";
      return internal;
    }),
    el => {
      if (parentPath) {
        el.setAttribute("data-parent-path", parentPath);
      }
      el.addEventListener("click", e => {
        if (window.RELATIVE.test(e.currentTarget.href)) {
          e.preventDefault();
          var virtualPath = e.currentTarget.href;

          window.view.current = virtualPath;
          return !!0;
        } else {
          return !!1;
        }
      });
    }
  );
};
