window.parseLinks = function(container) {

  var links = container.getElementsByTagName("a");
  Array.prototype.forEach.call(
    Array.prototype.filter.call(links, el => {
      console.log('target blank', el, el.target == '_blank');
      var internal = (window.RELATIVE.test(el.href) && el.getAttribute('data-force') != 'external') || el.getAttribute('data-force') == 'internal';
      if (!internal) {
        el.classList.add("external");
        el.target = '_blank';
      }
      el.style.display = "block";
      return internal;
    }),
    el => {
    
      el.addEventListener("click", e => {
        var forceInternal = el.getAttribute('data-force') == 'internal';
        var forceExtension = el.getAttribute('data-force-extension');
        if (window.RELATIVE.test(e.currentTarget.href) || forceInternal) {
          e.preventDefault();
          var virtualPath = e.currentTarget.href;

          virtualPath = forceInternal ? e.currentTarget.href.replace(/(http)s?:\/*/, 'external:') : virtualPath;
          virtualPath = forceExtension ? virtualPath + ':' + forceExtension : virtualPath;
          window.view.current = virtualPath;
          return !!0;
        } else {
          return !!1;
        }
      });
    }
  );
};
