window.CBoard = {
  textArea: null,

  isOS: function() {
    return navigator.userAgent.match(/ipad|iphone/i);
  },

  createTextArea: function(text) {
    this.textArea = document.createElement("textArea");
    this.textArea.value = text;
    document.body.appendChild(this.textArea);
  },

  selectText: function() {
    var range, selection;

    if (this.isOS()) {
      range = document.createRange();
      range.selectNodeContents(this.textArea);
      selection = window.getSelection();
      selection.removeAllRanges();
      selection.addRange(range);
      this.textArea.setSelectionRange(0, 999999);
    } else {
      this.textArea.select();
    }
  },

  copyToClipboard: function() {
    document.execCommand("copy");
    document.body.removeChild(this.textArea);
  },

  copy: function(text) {
    this.createTextArea(text);
    this.selectText();
    this.copyToClipboard();
  }
};
